version: '3.8'
services:
  api-server:
    restart: always
    build: ../../..
    ports:
    - 6000:6000
    command: "/main -port 6000 -debug true -scanner-url http://clair:6060 -reporter-url http://elasticsearch:9200"
    volumes:
      - ./conf/server.yaml:/config.yaml

  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    command: "-Dkeycloak.profile.feature.docker=enabled -b 0.0.0.0"
    container_name: keyclock
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    container_name: registry
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./certs/ca.crt:/root/certs/ca.crt
      - ./auth:/auth
      - ./conf/registry.yaml:/etc/docker/registry/config.yml

#  notary-server:
#    image: notary:server
#    ports:
#      - 8080:8080
#    command: "-Dkeycloak.profile.feature.docker=enabled -b 0.0.0.0"
#    container_name: notary-server
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#
#  notary-signer:
#    image: notary:signer
#    ports:
#      - 8080:8080
#    command: "-Dkeycloak.profile.feature.docker=enabled -b 0.0.0.0"
#    container_name: notary-server
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#
#  mysql:
#    image: mysql:5.7
#    container_name: mysql-compose
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#    healthcheck:
#      test: "mysql --user=root --execute 'SHOW DATABASES;'"
#      timeout: 20s
#      retries: 10
#    volumes:
#      - mysql-data:/var/lib/mysql